name: Docs

on: [push]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master


      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@ecff9f2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: BBtalkJS/BBtalkJS.github.io
          TARGET_BRANCH: master
          BUILD_SCRIPT: npm && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist
          CNAME: bb.js.org
